---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-deployment
  labels:
    app: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryovq1287.azurecr.io/tripinsights/trips:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: OPENAPI_DOCS_URI
          value: http://$EXTERNAL_IP"
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trip-db-connection
              key: SQL_PASSWORD
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: trip-db-connection
              key: SQL_SERVER
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: trip-db-connection
              key: SQL_USER
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/secrets"
          readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-key-vault-secrets"

---
apiVersion: v1
kind: Service
metadata:
  name: trips-service
spec:
  selector:
    app: trips
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80