# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-key-vault-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: 74ccf35d-b3e6-4e7f-8f67-86cb9b84ec87   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: trips-keyvault-421182sd        # Set to the name of your key vault
    objects:  |
      array:
        - |
          objectName: sql-password
          objectType: secret
        - |
          objectName: sql-user
          objectType: secret
        - |
          objectName: sql-server
          objectType: secret
    tenantId: 9ad3937a-16da-4374-885d-70ba657ac968              # The tenant ID of the key vault
  secretObjects:                             
  - secretName: trip-db-connection   
    data:
    - key: SQL_PASSWORD                          
      objectName: sql-password
    - key: SQL_USER                          
      objectName: sql-user
    - key: SQL_SERVER                     
      objectName: sql-server                                      
    type: Opaque 