---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  labels:
    app: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryovq1287.azurecr.io/tripinsights/userprofile:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trip-db-connection
              key: SQL_PASSWORD
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: trip-db-connection
              key: SQL_SERVER
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: trip-db-connection
              key: SQL_USER
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
spec:
  selector:
    app: userprofile
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80